# Generated by Django 5.2.4 on 2025-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='discipline',
        ),
        migrations.AddField(
            model_name='group',
            name='discipline',
            field=models.ManyToManyField(to='grades.discipline', verbose_name='Дисциплина'),
        ),
    ]
