# Generated by Django 5.2.4 on 2025-07-13 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_group_discipline_group_discipline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='professor',
        ),
        migrations.AddField(
            model_name='discipline',
            name='professors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
    ]
